# Generated by Django 5.2.11 on 2026-02-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RouteCache",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("route_hash", models.CharField(db_index=True, max_length=64, unique=True)),
                ("start_location", models.CharField(max_length=255)),
                ("end_location", models.CharField(max_length=255)),
                ("route_geometry", models.JSONField()),
                ("total_distance", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["route_hash"], name="routing_rou_route_h_196c1a_idx"),
                    models.Index(fields=["created_at"], name="routing_rou_created_2cb8cf_idx"),
                ],
            },
        ),
    ]
