# Generated by Django 5.2.11 on 2026-02-11 13:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FuelStation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("opis_id", models.IntegerField(db_index=True, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(db_index=True, max_length=100)),
                ("state", models.CharField(db_index=True, max_length=2)),
                ("retail_price", models.DecimalField(decimal_places=5, max_digits=6)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
                ),
                (
                    "geocode_status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("success", "Success"), ("failed", "Failed")],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("geocode_attempts", models.IntegerField(default=0)),
                ("geocode_last_error", models.TextField(blank=True, null=True)),
                ("geocoded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["state", "city"], name="stations_fu_state_64a61f_idx"),
                    models.Index(fields=["geocode_status"], name="stations_fu_geocode_9ec26d_idx"),
                ],
            },
        ),
    ]
